// ACTION TYPES FOR ADDING A NEW COMMENT TO A SPECIFIC DISH
export const ADD_COMMENT = "ADD_COMMENT";

// ACTION TYPES FOR DISHES
export const DISHES_LOADING = "DISHES_LOADING";
export const DISHES_FAILED = "DISHES_FAILED";
export const ADD_DISHES = "ADD_DISHES";

// ACTION TYPES FOR COMMENTS
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";

// ACTION TYPES FOR PROMOTIONS
export const PROMOS_LOADING = "PROMOS_LOADING";
export const ADD_PROMOS = "ADD_PROMOS";
export const PROMOS_FAILED = "PROMOS_FAILED";

// ACTION TYPES FOR LEADERS
export const LEADERS_LOADING = "LEADERS_LOADING";
export const ADD_LEADERS = "ADD_LEADERS";
export const LEADERS_FAILED = "LEADERS_FAILED";

// ACTION TYPES FOR FAVORITES
export const FAVORITES_LOADING = "FAVORITES_LOADING";
export const ADD_FAVORITES = "ADD_FAVORITES";
export const FAVORITES_FAILED = "FAVORITES_FAILED";

// ACTION TYPES FOR REGISTRATION
export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";

// ACTION TYPES FOR LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// ACTION TYPES FOR LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// ACTION TYPES FOR FEEDBACK
export const ADD_FEEDBACK = "ADD_FEEDBACK";
